### ISSUE TITLE
rotated soccer markings

### ISSUE THREAD

**Issue by Klumbumbus** [giggls/openstreetmap-carto-de#1]
the soccer marking lines on this pitch are 90 degree rotated: http://www.openstreetmap.org/way/15093305
![de_pitch](https://cloud.githubusercontent.com/assets/7115609/16113358/2b452bf0-33bc-11e6-8175-37fdd6623d89.png)
(screenshot from http://osm.geggus.net/map/ osm data openstreetmap contributors ODbL)

**Comment by giggls** [comment]
I know of this and I don't have the slightest idea why this is broken here but not in the old style. Rendering rules seem to be exactly the same. Looks like I have to re-enable the old style on my dev machine.

**Comment by Klumbumbus** [comment]
Before you adjusted the size of the pitch the french style didn't diaplay the lines at all. Now it displays it correctly. http://tile.openstreetmap.fr/?q=DJK%20Durlach&zoom=18&lat=49.00457&lon=8.48297&layers=B0000000FFFFFF

**Comment by giggls** [comment]
Check out https://github.com/cquest/osmfr-cartocss/blob/master/golf.mss and the SQL query in https://github.com/cquest/osmfr-cartocss/blob/master/project.mml This is where the code once originated from. However Max did some fixes during soccer WM 2014 to make the code work in southern and northern hemispheres as well.

**Comment by giggls** [comment]
The problem does not exist in newer versions of node-carto so I will close this as invalid.
