### ISSUE TITLE
highway=proposed at z12 looks like a real street

### ISSUE THREAD

**Issue by Klumbumbus** [giggls/openstreetmap-carto-de#11]
See proposed street south from Pirna
Probably highway=proposed shouldn't render at z12 at all?
https://www.openstreetmap.de/karte.html?zoom=12&lat=50.93901&lon=13.94221&layers=B000TT
![proposed_pirna](https://cloud.githubusercontent.com/assets/7115609/18794135/6016ce9c-81be-11e6-8e01-2d8a33da87f2.png)

**Comment by giggls** [comment]
Do you consider the width OK in higher zoomlevels? Currently proposed_casing_factor is independent of the zoom-level. It would be easy to change it from 3 to 2, but this will result in lighter rendering on higher zoomlevels as well. See line 336 ff. in roads.mss

**Comment by Klumbumbus** [comment]
This is hard to imagine and I cannot render and test it myself.
I think that it could look better on the higher zoom levels with factor 2. Especially at z17-18 the casing is pretty strong for a non existing object. Regarding z12 I think it would still be confusing even with factor 2.

**Comment by giggls** [comment]
OK, here is how it looks like using a proposed_casing_factor of 2. I would consider it usable for higher zoomlevels as well.

![mapnik-12-2206-1372](https://cloud.githubusercontent.com/assets/7996314/18800506/a849586e-81dd-11e6-9542-473512884168.png)

**Comment by Klumbumbus** [comment]
This looks like a small trunk, so I would remove it from z12 completely (and maybe use factor 2 at z13-18).

**Comment by giggls** [comment]
Stuff like this is often a matter of personal taste. I agree, that the current rendering is somewhat too prominent, thus I reduced the linewith factor to 1.0 for z12 and 2.0 for higher levels.
If you still don't like it get yourself a rendering stack and send pull requests :)

**Comment by Klumbumbus** [comment]
Alright, sir ;)
