### ISSUE TITLE
highway=primary is thiner than highway=secondary at z18

### ISSUE THREAD

**Issue by Klumbumbus** [giggls/openstreetmap-carto-de#12]
This results in "secondary-stumps" at the othe side of the primary.
https://www.openstreetmap.de/karte.html?zoom=18&lat=50.62847&lon=12.82637&layers=B000TT
![secondary_stupms](https://cloud.githubusercontent.com/assets/7115609/18794356/6edf9840-81bf-11e6-962e-228bd2af37a2.png)

**Comment by giggls** [comment]
OK, this is crap. I will adjust the width of primary-tertiary accordingly.
