### ISSUE TITLE
Kreisverkehr 

### ISSUE THREAD

**Issue by JoergFF** [giggls/openstreetmap-carto-de#15]
Hi,

einige Straßen an einem Kreisverkehr werden in den Kreis gezeichnet.
Bei den beiden Beispielen enden die angebundenen Straßen korrekt am Kreisverkehr.
 
![kreisverkehr bernkastel-kues 1](https://cloud.githubusercontent.com/assets/7426044/18860854/27b1490e-8481-11e6-98f1-ac7b10b47820.png)
![kreisverkehr bernkastel-kues 2](https://cloud.githubusercontent.com/assets/7426044/18860855/27b4366e-8481-11e6-8553-b8c9ad8c6f49.png)

**Comment by giggls** [comment]
As I already wrote in issue 16. lease include a Tile URL. Does the Problem exist on upstream?

**Comment by giggls** [comment]
OK, I further investigated this. Also not a style issue. For some reason these ways seem to be wrong in my database. Also happens with upstream style and my database. Thus I will also close this.
![mapnik-19-272441-178000](https://cloud.githubusercontent.com/assets/7996314/18866088/920191f2-849e-11e6-8a1d-84efcb437d6d.png)
