### ISSUE TITLE
Kleingärten werden nicht immer gerendert

### ISSUE THREAD

**Issue by hholzgra** [giggls/openstreetmap-carto-de#22]
Im CartoOSM Stil sind sie drin ... hab jetzt nicht genauer in den Style Files nachgeschaut, vermute mal das liegt daran dass der Schloßhof-Kleingarten mit access=permissive getagged ist?

http://tools.geofabrik.de/mc/#17/52.0337/8.5162&num=2&mt0=mapnik&mt1=mapnik-german

**Comment by gmbo** [comment]
oder weil landuse=residential den Kleingarten einschließt, wie bei Mischwald in einer großen Fläche Nadelwald.

**Comment by hholzgra** [comment]
Das wäre dann aber in diesem Fall aber sowohl beim sichtbaren als auch beim unsichtbaren Kleingarten der Fall ...

**Comment by giggls** [comment]
Kein Bug im Stil sondern ein Problem mit meiner Datenbank. Beim initialen Import sind eine Hand voll changesets verloren gegangen, da waren Deine Kleingärten wohl zufällig dabei. es dürfte helfen irgendeine Kleinigkeit zu ändern :)
