### ISSUE TITLE
Missing column junction in polygon-view

### ISSUE THREAD

**Issue by rrzefox** [giggls/openstreetmap-carto-de#29]
Current master will probably not work, because it needs a column 'junction' in the polygon-table - which the current view_polygon.sql does not set up.
It will probably need something like
`tags->'junction' as "junction",`
else it ends like this:
`Postgis Plugin: ERROR:  column "junction" does not exist#012LINE 14:     junction,#012             ^#012HIN
T:  There is a column named "junction" in table "*SELECT* 1", but it cannot be referenced from this part of the query. [...]  encountered during parsing of layer 'junctions' in Layer at line 51315`

**Comment by giggls** [comment]
*argh* I already fixed this on my dev machine obviously. I will push an update
