### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by pnorman** [giggls/openstreetmap-carto-de#3]
`get_localized_placename`, `get_localized_name_without_brackets`, and `get_localized_streetname` are not defined in mapnik-german-l10n or this repo.

**Comment by pnorman** [comment]
`get_latin_name` too.

**Comment by giggls** [comment]
Jepp. l10n functions have been renamed to avoid namespace pollution inside the PostgreSQL database. I have just pushed a change which fixes the views.
I also have the mid-term goal to make the l10n stuff a postgres extension, thats another reason for a unified function namespace.

**Comment by giggls** [comment]
l10n stuff is now a postgresql extension and database views have been renamed to match the upstream table names.
