### ISSUE TITLE
Some column names are missing from the database

### ISSUE THREAD

**Issue by asimeqi** [giggls/openstreetmap-carto-de#32]
This style queries for columns such as localized_name_first or localized_name_second which are not in the database. From reading some of the other issues I understand that there might be some scripts to create those columns but I don't see those scripts in the repository.

**Comment by giggls** [comment]
Did you read https://github.com/giggls/openstreetmap-carto-de/blob/master/INSTALL-de.md on the first place?

In contrast to upstream carto style this style does not use the tables directly for rendering. Instead you should use the provided views. It is also required to install the osml10n extension to your database to make it work.

Starting from Carto 4.0 it is now even possible to use the upstream database layout. See https://github.com/giggls/openstreetmap-carto-de/blob/master/contrib/use-upstream-database/README.md for details.

**Comment by asimeqi** [comment]
Thanks that was very helpful.
