### ISSUE TITLE
Undo request

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [giggls/openstreetmap-carto-de#33]
I am asking for undoing this commit: https://github.com/giggls/openstreetmap-carto-de/commit/fddd481f338678d6136a401469e86aa047dc91a5

The problem there relies on unbeautiness in Uruguay and Argentina borders and some waters - that change dramatically increase rendering times between z0 and z6, in my case the z0 render time increased from 0.155s to 370.529s - that is 2390x slower.

I don't know if we need this slow-down change in a *german* style. Please re-consider the pull request.

**Comment by giggls** [comment]
Did you report this upstream? In openstreetmap-carto-de this is just a merge from upstream carto.

**Comment by it-solutions-zehaczek** [comment]
I commented the original pull request: https://github.com/gravitystorm/openstreetmap-carto/pull/2873

**Comment by giggls** [comment]
I'm aware of the problem and would have like to see something along the line of Christophs suggestions: http://blog.imagico.de/parting-the-waters/ 
My Problem in German style is that I have to be close enough to standard style to allow for reasonably easy merging.

**Comment by kocio-pl** [comment]
https://github.com/gravitystorm/openstreetmap-carto/issues/2507 is probably how it should be done, but no participant of this discussion is currently active in osm-carto and nobody answered when I asked there, so I don't know what's the plan at the moment. Maybe you could just talk with them directly.

**Comment by giggls** [comment]
@it-solutions-zehaczek: I merged the work from @imagico (Low Zoom waterbodies and water instead of land polygons) into dev-de branch. I will likely also merge this into my master branch. You might give this a try.

**Comment by it-solutions-zehaczek** [comment]
Ok thx, i'll check this out within the next days.
