### ISSUE TITLE
mapnik-german-l10n updated

### ISSUE THREAD

**Issue by werk21** [giggls/openstreetmap-carto-de#38]
mapnik-german-l10n is updated and the sql-statements in views_osmde are not adapted.

This works for me:

`osml10n_get_placename_from_tags(tags, true, false, chr(10), 'de', way) as localized_name_inside_brackets,`
`osml10n_get_placename_from_tags(tags, false, false, chr(10), 'de', way) as localized_name_outside_brackets,`
`osml10n_get_name_without_brackets_from_tags(tags, 'de', way) as localized_name_without_brackets,`
`osml10n_get_streetname_from_tags(tags, true, false, chr(10), 'de', way) as localized_streetname_inside_brackets,`
`osml10n_get_streetname_from_tags(tags, false, false, chr(10), 'de', way) as localized_streetname_outside_brackets,`

**Comment by giggls** [comment]
Non of the following columns are use in the the current version of the style:

- localized_name_inside_brackets
- localized_name_outside_brackets
- localized_streetname_inside_brackets
- localized_streetname_outside_brackets

So I see no need to add them to the views.

"localized_name_without_brackets" is used, but is present in all four views.

So where is the issue?

**Comment by werk21** [comment]
Big sorry, wrong project. The problems are in https://github.com/rory/openstreetmap-carto-de
Just close this tickets.
ky.
