### ISSUE TITLE
Install instructions result in table name mismatch

### ISSUE THREAD

**Issue by pnorman** [giggls/openstreetmap-carto-de#4]
The install instructions put osm2pgsql tables in place with a planet_osm prefix, but queries like landcover low zoom are of the form `(SELECT ... localized_name_without_brackets AS name FROM planet_osm_polygon WHERE ...) AS landcover_low_zoom`.

I recommend setting an osm2pgsql prefix and then creating views with the normal table names as this avoids the need to make a bunch of project.yaml changes which will need to be kept in sync.

**Comment by giggls** [comment]
project.yaml in my fork is not intended to be actually used. Instead the Table/view names to be used are inserted by the replace_table_and_database_names script which will create the project-de.yaml.
Rationale behind this is that project.yaml should be as close to upstream as possible so there should be no different table names inside this file. So just use make.

**Comment by pnorman** [comment]
> So just use make

The instructions need to be changed to cover this then.

I also advise against using complicated pre-processing like this, it adds a significant barrier to new contributions.

**Comment by giggls** [comment]
I now, that documentation needs to be improved. The sole reason for using a Makefile and pre-processing is to keep projekt.yaml as close to upstream as possible .
