### ISSUE TITLE
Config periodic updates

### ISSUE THREAD

**Issue by OsamaShabrez** [giggls/openstreetmap-carto-de#42]
I am following [OSM Wiki guide](https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1804_tileserver_load) after setting up my tile server for periodic updates. It complains of unavailable relations, here is the log

```
[2019-07-12 10:09:59] 18576 Initialising Osmosis replication system to 2019-07-04T01:00:00Z
[2019-07-12 10:10:27] 18967 start import from seq-nr 3566977, replag is 8 day(s) and 7 hour(s)
[2019-07-12 10:10:27] 18967 downloading diff
[2019-07-12 10:18:09] 18967 filtering diff
Traceback (most recent call last):
  File "/home/sbw/src/regional/trim_osc.py", line 121, in <module>
    cur.execute('select id from planet_osm_nodes where id = ANY(%s);', (nodesM,))
psycopg2.ProgrammingError: relation "planet_osm_nodes" does not exist
LINE 1: select id from planet_osm_nodes where id = ANY('{}');
                       ^

[2019-07-12 10:18:10] 18967 [error] Trim_osc error
[2019-07-12 10:18:10] 18967 resetting state
```

I understand this is because we use hstore and all tables have it prefixed. Do we a different way of updating tile servers following this style or should I just update the table names inside [trim_osc.py](https://github.com/Zverik/regional/blob/master/trim_osc.py) for nodes, ways and relations?
Anything else I should be worried about?

**Comment by giggls** [comment]
This is neither a German map style issue nor an upstream map style issue.
I do not even know what trim_osc.py is for.

**Comment by OsamaShabrez** [comment]
If you follow the installation guide for this map style. Periodic updates break and complain of unavailable relations. How is this not an issue?

**Comment by giggls** [comment]
These issues here are about the map style and in particular about the German style fork of the carto map style!
This might well be an issue for you, but is not an issue of the map style and thus off-topic here.

**Comment by giggls** [comment]
To explain my somewhat rough answer in more detail. While your question is certainly off-topic I would have been unable to answer it anyway, because I'm not using the setup in the Wiki where your link points to.
For German tileservers I use https://github.com/openstreetmap/tirex instead of renderd and the scripts available at https://github.com/giggls/tileserver-scripts for database replication.
