### ISSUE TITLE
road width inconsistency at Z=14

### ISSUE THREAD

**Issue by poempelfox** [giggls/openstreetmap-carto-de#45]
At Zoomlevel 14, secondary roads render visibly wider than primary roads. That creates a rather inconsistent and confusing look (if it's a much smaller road, why is it drawn twice as wide?).

Example:
https://www.openstreetmap.de/karte.html?zoom=14&lat=28.66291&lon=-17.76286&layers=B000TF
![osm-carto-de1](https://user-images.githubusercontent.com/4013374/67456315-ab0b0500-f630-11e9-9421-a497761d1901.png)

(edit: this does not appear to happen in the upstream style, probably because the roads there are generally drawn much thinner)

**Comment by poempelfox** [comment]
Yes, this really only hit my eye on Z14. And changing to upstream-width is probably the easiest fix, although it will make them somewhat thinner than they are now. Sorry, no further clearly smart suggestions.

**Comment by giggls** [comment]
https://gauss.openstreetmap.de/#map=14/28.6773/-17.7719/2
