### ISSUE TITLE
Issues with missing fonts

### ISSUE THREAD

**Issue by Fauch922** [giggls/openstreetmap-carto-de#53]
Some parts of my map are showing squares instead of the original names, e.g.:

Pakistan, Cambodia, some countries in North Africa. I'm assuming this is due to missing fonts.  I cannot figure out which fonts are missing. I have installed the following fonts:

- dejavu
- font-awesome
- freefont
- hanazono
- lato
- lyx
- noto
- unifont

I'm using openstreetmap-carto-de and the i10n plugin.

I have installed (most) of these fonts using 

`sudo apt-get install fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted fonts-hanazono ttf-unifont`

my renderd.conf includes the following lines:

```
[mapnik]
plugins_dir=/usr/lib/mapnik/3.0/input
font_dir=/usr/share/fonts/truetype
font_dir_recurse=true

```

### Expected behavior
I'm expecting all names in their original language to be rendered correctly.

### Actual behavior

The names aren't rendered correctly. Renderd shows no errors at all. Some names are rendered correctly at a certain layer, then the wrong way again at a different layer.

### Links and screenshots illustrating the problem

[Cambodia example](https://imgur.com/ZGbRwfs)

**Comment by giggls** [comment]
There is no difference between fonts needed by upstream and German Style Fork.

As I do not use renderd (which is mostly unmaintained) I can not help here.

Try rendering using nik2img.

**Comment by Fauch922** [comment]
Thank you for your swift answer. 

`render_single_tile.py` did indeed help resolve the issue. There were several missing fonts that were not covered either by the packages you listed nor by the packages I had installed already.

These fonts were:

- "unifont Medium"
- "Noto Sans Syriac Eastern Regular"
- "Noto Sans Balinese Regular"
- "Noto Emoji Regular"

Removing these fonts from the stylesheet (osm-de.xml) resolved the issue. 
Thank you for your help.

**Comment by giggls** [comment]
Well at least on Debian "Noto Sans Balinese Regular" and "Noto Sans Syriac Eastern Regular" are part of the fonts-noto-core package.

You can ignore the warnings regarding "unifont Medium".

As you write this I remember adding the Emoji fonts manually as well.

This said I will close this now because this has never been an issue of this style anyway.
