### ISSUE TITLE
Tile download throws CORS error

### ISSUE THREAD

**Issue by ptkz** [giggls/openstreetmap-carto-de#58]
### Expected behavior
I should be able to create a screenshot from the map.

### Actual behavior
The map loads perfectly, but when I try to create a screenshot of the map, capturing the Map's DOM with [`dom-to-image`](https://www.npmjs.com/package/dom-to-image) to export it, it throws a CORS error: 
`Access to XMLHttpRequest at 'https://a.tile.openstreetmap.de/tiles/osmde/3/6/3.png' from origin 'https://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
The same is true in our QA and staging environment too.

It could be fixed if you would add `access-control-allow-origin: *` to the server response headers.
This is already set with other OSM map types, thus those are working correctly for my use case.

**Comment by giggls** [comment]
This is not the place to discuss issues of tile.openstreetmap.de.

**Comment by giggls** [comment]
I just tried with curl:
```
 ~/ > curl --head https://tile.openstreetmap.de/6/33/21.png
HTTP/1.1 200 OK
Date: Tue, 08 Feb 2022 10:33:24 GMT
Server: Apache/2.4.38 (Debian)
ETag: "16427c725d70479359fecd0aacb92973"
Content-Length: 56612
Cache-Control: max-age=259429
Expires: Fri, 11 Feb 2022 10:37:13 GMT
Access-Control-Allow-Origin: *
Content-Type: image/png
```

**Comment by giggls** [comment]
Found what your problem is. You are using the wrong tile url which gives you a
301 Moved Permanently which does not have an Access-Control-Allow-Origin header.

**Comment by ptkz** [comment]
Hi @giggls , thanks for the fast response.

Changed the request url
From: `https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png`
To: `https://{s}.tile.openstreetmap.de/{z}/{x}/{y}.png`

Works like a charm!
Thank you!
