### ISSUE TITLE
Line 59: Wrong URL of get-shapefiles.py 

### ISSUE THREAD

**Issue by walxo** [giggls/openstreetmap-carto-de#59]

**Comment by walxo** [comment]
Something wrong with URL in line 59:
'url': 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip', # noqa

Browsers are able to download the file, but running get-shapefiles.py script return an error:
Error: download failed. (error code: 406, error reason: Not Acceptable)

**Comment by giggls** [comment]
Running curl -v instead of blindly reporting bugs here would have revealed the new URL. I will push a a changed version.
