### ISSUE TITLE
docker-compose up import  issue

### ISSUE THREAD

**Issue by toqeer786** [giggls/openstreetmap-carto-de#65]
hi i want to run this project through docker i am follwoing the DOCKER.md file first of all when i run this command 
:docker-compose up import i have the following error mentioned in screenshot kindly tell me what thing i had missed ,, am using the docker 1st time 
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.kosmtik: 'platform

![docker issue](https://user-images.githubusercontent.com/115454250/201270763-428a8faf-9177-42a8-afa4-a4a27165dff8.png)

note (i am using ubuntu 20.04 in oracle virtual-box

**Comment by giggls** [comment]
Docker is untested with this fork. Will almost certainly not work and is not unsupported.
Looks like I need to clarify this in the README.
