### ISSUE TITLE
error loading project.mml file 

### ISSUE THREAD

**Issue by toqeer786** [giggls/openstreetmap-carto-de#66]
hello i have comleted the all installation steps but at the end when i  wants run kosmitik to serve project.mml file i have the following errors 
the command i had run :  node index.js serve ../openstreetmap-carto-de/project.mml
 and the error i had 

note ( osm2pgsql version 1.7.1 )
and one thing more i already have  the fonts and also enabled through command:scripts/get-fonts.sh

you can also see the this 

![image](https://user-images.githubusercontent.com/115454250/201312990-d5a83e11-0760-4988-9294-af6f9e5a77cc.png)

kindly help

**Comment by giggls** [comment]
Did you try running make test?

**Comment by giggls** [comment]
There are no 87 tests in the Makefile of this project.
I am *not* talking about l10n.

**Comment by giggls** [comment]
I have not been using kosmtik for a long time. Might well be broken.
Try rendering single tiles using make test.

**Comment by toqeer786** [comment]
> I have not been using kosmtik for a long time. Might well be broken. Try rendering single tiles using make test.

can you please explain how can i run make test as you suggest

**Comment by giggls** [comment]
I do not understand this question. There is a Makefile in this repository so the explanations would be to type ``make test``?

**Comment by toqeer786** [comment]
> I do not understand this question. There is a Makefile in this repository so the explanations would be to type `make test`?

Dear Sir i have run this command but i have another error kinldy check please
![image](https://user-images.githubusercontent.com/115454250/201320893-58240cbf-62cf-4b85-8a0e-af94a3420bda.png)

**Comment by giggls** [comment]
Please do not post screenshots here but plain text only.
Sorry for getting angry now, but do you actually *read* what your computer tells you?
This is not a support forum for general Linux problems. This is a bugtracker for the German Version of osm-carto.

1. Why the hell are you trying to run this as root?
2. If carto is not available try ``npm install carto``

Thinking about error messages before posting questions might actually help!
