### ISSUE TITLE
lua errors when trying to run osm2pgsql

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [giggls/openstreetmap-carto-de#67]
### Expected behavior
osm2pgsql is importing data using your preinstalled osml10n scripts

### Actual behavior
lua errors

```
2022-11-23 16:18:12  osm2pgsql version 1.7.2 (1.7.2-17-gce5feeeb)
2022-11-23 16:18:12  Database version: 13.8 (Debian 13.8-0+deb11u1)
2022-11-23 16:18:12  PostGIS version: 3.1
2022-11-23 16:18:12  ERROR: Error loading lua config: ...cal/src/openstreetmap-carto-de/openstreetmap-carto.style:2: unexpected symbol near '#'.
```

If i ommit the "-O flex" option, i get:

```
2022-11-23 16:18:24  osm2pgsql version 1.7.2 (1.7.2-17-gce5feeeb)
2022-11-23 16:18:24  Database version: 13.8 (Debian 13.8-0+deb11u1)
2022-11-23 16:18:24  PostGIS version: 3.1
2022-11-23 16:18:24  ERROR: Lua tag transform style error: ...cal/src/osml10n/openstreetmap-carto-hstore-only-l10n.lua:63: attempt to index a nil value (global 'osm2pgsql').
```

osml10n.service is up and running

### Links and screenshots illustrating the problem

```
/usr/local/bin/osm2pgsql --version
2022-11-23 16:18:00  osm2pgsql version 1.7.2 (1.7.2-17-gce5feeeb)
Build: RelWithDebInfo
Compiled using the following library versions:
Libosmium 2.17.3
Proj [API 4] Rel. 7.2.1, January 1st, 2021
Lua 5.3.3
```

```
lua -v
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
```

If i use the tag transform script from this repo ([openstreetmap-carto.lua](https://github.com/giggls/openstreetmap-carto-de/blob/master/openstreetmap-carto.lua)), the import runs without errors, but then hstore tables are missing when creating the views.

**Comment by it-solutions-zehaczek** [comment]
I have read and tried everything forth and back and spent the whole day in what is possibly going wrong, i am stuck.

**Comment by it-solutions-zehaczek** [comment]
Don't worry i've read all your -de's texts (and the upstream too and much more).

The actual command was:

`sudo -u _renderd /usr/local/bin/osm2pgsql -G --number-processes 8 -d tiles -U _renderd -C 8192 -S /usr/local/src/openstreetmap-carto-de/openstreetmap-carto.style -O flex --tag-transform-script /usr/local/src/osml10n/openstreetmap-carto-hstore-only-l10n.lua /usr/local/share/osm/liechtenstein-latest.osm.pbf`

Output as mentioned above

**Comment by giggls** [comment]
This command is complete utter crap :(

Try reading flex manual to understand what we are doing here.

Translating my Example from INSTALL.md I end up with something like this:

``
sudo -u _renderd /usr/local/bin/osm2pgsql -G --number-processes 8 -d tiles -U _renderd -C 8192 -S  /usr/local/src/osml10n/openstreetmap-carto-hstore-only-l10n.lua  -O flex /usr/local/share/osm/liechtenstein-latest.osm.pbf
``

**Comment by it-solutions-zehaczek** [comment]
ARGH. this works. didn't see i have to pass the lua as style, dammit. My head is exploding of all this different guides and versions and texts and i am working on migrating an old postgres 9.6 installation for weeks now (including nominatim and overpass). I am totally messed up. Thank you.
