### ISSUE TITLE
how to generate osm-de.xml from project.mml 

### ISSUE THREAD

**Issue by toqeer786** [giggls/openstreetmap-carto-de#69]
how we can generate osm-de.xml from the project.mml file i had read the install.md here [](https://github.com/giggls/openstreetmap-carto-de/blob/master/INSTALL-de.md)
my question is that what command will be used to generate it ,kindly help

**Comment by giggls** [comment]
Just type make.

**Comment by toqeer786** [comment]
> Just type make.
Hello !!! 
this command have the following errors when i run it.
 > make
carto -a 3.0.15 project.mml > /tmp/tmp.lVm9dVHgng
/usr/lib/nodejs/carto/lib/carto/tree/reference.js:19
    if (mapnik_reference.version.hasOwnProperty(version)) {
                                 ^

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.ref.setVersion (/usr/lib/nodejs/carto/lib/carto/tree/reference.js:19:34)
    at /usr/lib/nodejs/carto/lib/carto/tree/reference.js:209:5
    at Object.<anonymous> (/usr/lib/nodejs/carto/lib/carto/tree/reference.js:213:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
make: *** [Makefile:19: osm-de.xml] Error 1
>

**Comment by giggls** [comment]
Unfortunately I can not help with issues out of the blue air as I do not now anything about the environment you are using. Especially as there are no such problems compiling projekt.mml in my environment (Debian GNU/Linux 11 and Carto version 1.2.0).

Please try compiling upstream style (carto project.mml) in your environment and come back here if it **does work** there but does **not work** in this fork here.

BTW, debugging Carto or Mapnik issues is also off-topic in upstream style issue tracker.

Regards

Sven

**Comment by toqeer786** [comment]
> here

how we can use upstream style with this project ?

**Comment by giggls** [comment]
I want to know if it is possible to **compile** upstream project.mml with your setup I have not been talking about using it.

I suppose that this will not work also, as this is almost certainly a Carto or Mapnik setup issue and not really a style issue.
